version: '3.8'
services:
  postgres:
    container_name: 'ctrl-x-postgres'
    image: 'postgres:14-alpine'
    ports:
      - '5432:5432'
    volumes:
      - 'ctrl_x:/var/lib/postgresql/data:rw'
    environment:
      - 'POSTGRES_USER=${POSTGRES_USER:-admin}'
      - 'POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-admin}'
      - 'POSTGRES_DB=ctrl-x'

  rabbitmq:
    image: rabbitmq:latest
    container_name: 'ctrl-x-rabbitmq'
    environment:
      - 'RABBITMQ_DEFAULT_USER=${RABBITMQ_USER:-admin}'
      - 'RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS:-admin}'
    volumes:
      - 'ctrl-x-rabbitmq/etc/:/etc/rabbitmq/'
      - 'ctrl-x-rabbitmq/data/:/var/lib/rabbitmq/'
      - 'ctrl-x-rabbitmq/logs/:/var/log/rabbitmq/'
    ports:
      - '5672:5672'
      - '15672:15672'

volumes:
  ctrl_x:
